name: Build

on: [push]
env:
  BUILD_TYPE: MinSizeRel

jobs:
  # === Windows PRO ===
  windows-pro:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build
        shell: cmd
        run: |
          cd build
          cmake -G "Visual Studio 16 2019" -DBUILD_SDLGPU=On -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_PRO=On ..
          cmake --build . --config %BUILD_TYPE% --parallel

      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-windows-pro"
          path: build/bin/tic80.exe

  # === Export ===
  export:
    needs: [windows-pro]
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: tic80-windows-pro
          path: windir

      - name: Rename
        run: |
          cp windir/* win

      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-export"
          path: |
            win

  # === Export stub ===
  export-stub:
    needs: [export]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [lua, moon, fennel, ruby, js, wren, squirrel, wasm, scheme, janet, python]

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: tic80-windows-pro-stub
          path: windir

      - name: Rename
        run: |
          cp windir/tic80${{ matrix.script }}.exe win${{ matrix.script }}

      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-export"
          path: |
            win${{ matrix.script }}


  # === Delete stub artifacts ===
  delete-stub:
    needs: [export-stub]
    runs-on: ubuntu-latest

    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            tic80-windows-pro-stub
